apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
  labels:
    name: flask-app-service
spec:
  ports:
    - protocol: TCP
      port: 5051
      targetPort: 5000
  selector:
    app: flask-app
  type: NodePort
